server:
  port: 8080
  servlet:
    context-path: /api/notifications

spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://${HOST}:${PORT:5432}/${DB_NAME}?currentSchema=${SCHEMA}
    driver-class-name: org.postgresql.Driver
    username: ${USERNAME}
    password: ${PAROL}

    hikari:
      minimum-idle: 2
      idle-timeout: 40000
      maximum-pool-size: 10
      connection-timeout: 10000
      keepalive-time: 30000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: ${SCHEMA}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false


