spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/app-db?currentSchema=notifications_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: notifications_db
    database-platform: org.hibernate.dialect.PostgreSQLDialect